server:
    port: 8888
spring:
    rabbitmq:
        host: localhost
        port: 5672
hystrix:
    command:
        default:
            execution:
                timeout:
                    enabled: false 
management:
    security:
        enabled: false
