eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka/
server:
    port: 8889
spring:
    rabbitmq:
        host: localhost
        port: 5672
hystrix:
    command:
        default:
            execution:
                timeout:
                    enabled: false 
management:
    security:
        enabled: false
